# Generated by Django 2.0.3 on 2018-04-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=250)),
                ('related_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yojna.Field')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='yojna_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lower_age', models.IntegerField(default=-1)),
                ('upper_age', models.IntegerField(default=-1)),
                ('salary_min', models.IntegerField(default=-1)),
                ('salary_max', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='yojna_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yojna.problem')),
                ('yojna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yojna.yojna_desc')),
            ],
        ),
        migrations.CreateModel(
            name='yojna_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yojna.state')),
                ('yojna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yojna.yojna_desc')),
            ],
        ),
    ]
